-- 게시판: 법인 (code: nt4)
-- 크롤링 일시: 2026-06-22 13:56:10
-- Base URL: http://namsanwon.or.kr/05/commu08.php

SET NAMES utf8mb4;

INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (38630,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (38553,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (38631,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (38552,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (37833,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (38007,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (36411,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (36410,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (37826,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (36321,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (35945,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (36311,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (34419,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (35697,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (34231,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (34236,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (33779,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (33669,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (34239,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (33160,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (31845,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (29724,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (31362,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (28906,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (28532,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (28533,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (27003,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (25366,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (25944,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (25127,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (22765,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (23450,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (22190,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (20779,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (19700,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (20138,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (18493,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (17719,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (17853,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (17718,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (16154,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (17302,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (15547,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (15123,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (13070,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (13508,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (12649,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (12045,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (11729,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (11567,'nt4','','','','',0,0,'', '', '', '', '', '');
INSERT INTO `wiz_bbs` (`idx`,`code`,`name`,`email`,`subject`,`content`,`count`,`wdate`,`upfile1`,`upfile2`,`upfile3`,`upfile1_name`,`upfile2_name`,`upfile3_name`) VALUES (9924,'nt4','','','','',0,0,'', '', '', '', '', '');
